# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc14985f94205e7c205044e1e2b7978c"
application_url = "https://json-inspector-app.terenzzzz.cn"
embedded = true
name = "json-inspector"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_themes"

[auth]
redirect_urls = [
  "https://json-inspector-app.terenzzzz.cn/auth/callback",
  "https://json-inspector-app.terenzzzz.cn/auth/shopify/callback",
  "https://json-inspector-app.terenzzzz.cn/api/auth"
]

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[build]
automatically_update_urls_on_dev = true
